
import { Word } from './types';
import { EXTENDED_VOCABULARY } from './vocabulary-extended';
import { VOCAB_201_300 } from './vocabulary-201-300';
import { VOCAB_301_400 } from './vocabulary-301-400';
import { VOCAB_401_500 } from './vocabulary-401-500';

// Categories for better filtering
export const CATEGORIES = [
  'All', 'Greetings', 'Time', 'Nature', 'People', 'Verbs', 'Adjectives', 'Objects', 'Numbers'
];

export const VOCABULARY_DATA: Word[] = [
  { id: 1, spanish: 'Yo', transliteration: 'yo', malaysian: 'yo', meaning: 'I / Me', category: 'People', mnemonic: 'YO - I am me' },
  { id: 2, spanish: 'Tú', transliteration: 'too', malaysian: 'tu', meaning: 'You', category: 'People', mnemonic: 'TU - You are near' },
  { id: 3, spanish: 'Hola', transliteration: 'oh-lah', malaysian: 'hola', meaning: 'Hello', category: 'Greetings', mnemonic: 'HOLA - Oh-la to say hello' },
  { id: 4, spanish: 'Gracias', transliteration: 'grah-see-ahs', malaysian: 'gracias', meaning: 'Thank you', category: 'Greetings', mnemonic: 'GRACIAS - Grah-see-ahs for thanks' },
  { id: 5, spanish: 'Comer', transliteration: 'koh-mehr', malaysian: 'comer', meaning: 'To eat', category: 'Verbs', mnemonic: 'COMER - Koh-mehr to eat' },
  { id: 6, spanish: 'Beber', transliteration: 'beh-behr', malaysian: 'beber', meaning: 'To drink', category: 'Verbs', mnemonic: 'BEBER - Beh-behr to drink' },
  { id: 7, spanish: 'Agua', transliteration: 'ah-gwah', malaysian: 'agua', meaning: 'Water', category: 'Nature', mnemonic: 'AGUA - Ah-gwah is water' },
  { id: 8, spanish: 'Sol', transliteration: 'sohl', malaysian: 'sol', meaning: 'Sun', category: 'Nature', mnemonic: 'SOL - Sohl is the sun' },
  { id: 9, spanish: 'Luna', transliteration: 'loo-nah', malaysian: 'luna', meaning: 'Moon', category: 'Time', mnemonic: 'LUNA - Loo-nah is the moon' },
  { id: 10, spanish: 'Hoy', transliteration: 'oy', malaysian: 'hoy', meaning: 'Today', category: 'Time', mnemonic: 'HOY - Oy is today' },
  { id: 11, spanish: 'Mañana', transliteration: 'mah-nyah-nah', malaysian: 'manyana', meaning: 'Tomorrow', category: 'Time', mnemonic: 'MAÑANA - Mah-nyah-nah is tomorrow' },
  { id: 12, spanish: 'Ayer', transliteration: 'ah-yehr', malaysian: 'ayer', meaning: 'Yesterday', category: 'Time', mnemonic: 'AYER - Ah-yehr is yesterday' },
  { id: 13, spanish: 'Grande', transliteration: 'grahn-deh', meaning: 'Big', category: 'Adjectives', mnemonic: 'GRANDE - Grahn-deh is big' },
  { id: 14, spanish: 'Pequeño', transliteration: 'peh-keh-nyoh', meaning: 'Small', category: 'Adjectives', mnemonic: 'PEQUEÑO - Peh-keh-nyoh is small' },
  { id: 22, spanish: 'Profesor', transliteration: 'proh-feh-sohr', meaning: 'Teacher', category: 'People', mnemonic: 'PROFESOR - Proh-feh-sohr is teacher' },
  { id: 23, spanish: 'Estudiante', transliteration: 'es-too-dee-ahn-teh', meaning: 'Student', category: 'People', mnemonic: 'ESTUDIANTE - Es-too-dee-ahn-teh is student' },
  { id: 24, spanish: 'País', transliteration: 'pah-ees', meaning: 'Country', category: 'Nature', mnemonic: 'PAÍS - Pah-ees is country' },
  { id: 25, spanish: 'Idioma', transliteration: 'ee-dee-oh-mah', meaning: 'Language', category: 'Objects', mnemonic: 'IDIOMA - Ee-dee-oh-mah is language' },
  { id: 26, spanish: 'Casa', transliteration: 'kah-sah', malaysian: 'casa', meaning: 'House / Home', category: 'Objects', mnemonic: 'CASA - Kah-sah is home' },
  { id: 27, spanish: 'Escuela', transliteration: 'es-kweh-lah', malaysian: 'eskuela', meaning: 'School', category: 'Objects', mnemonic: 'ESCUELA - Es-kweh-lah is school' },
  { id: 28, spanish: 'Amor', transliteration: 'ah-mohr', meaning: 'Love', category: 'Greetings', mnemonic: 'AMOR - Ah-mohr is love' },
  { id: 29, spanish: 'Paz', transliteration: 'pahs', meaning: 'Peace', category: 'Greetings', mnemonic: 'PAZ - Pahs is peace' },
  { id: 30, spanish: 'Corazón', transliteration: 'koh-rah-sohn', meaning: 'Heart', category: 'People', mnemonic: 'CORAZÓN - Koh-rah-sohn is heart' },
  { id: 31, spanish: 'Ir', transliteration: 'eer', meaning: 'To go', category: 'Verbs', mnemonic: 'IR - Eer to go' },
  { id: 32, spanish: 'Venir', transliteration: 'beh-neer', meaning: 'To come', category: 'Verbs', mnemonic: 'VENIR - Beh-neer to come' },
  { id: 33, spanish: 'Ver', transliteration: 'behr', meaning: 'To see', category: 'Verbs', mnemonic: 'VER - Behr to see' },
  { id: 34, spanish: 'Oír', transliteration: 'oh-eer', meaning: 'To hear', category: 'Verbs', mnemonic: 'OÍR - Oh-eer to hear' },
  { id: 35, spanish: 'Hablar', transliteration: 'ah-blahr', meaning: 'To speak', category: 'Verbs', mnemonic: 'HABLAR - Ah-blahr to speak' },
  { id: 36, spanish: 'Leer', transliteration: 'leh-ehr', meaning: 'To read', category: 'Verbs', mnemonic: 'LEER - Leh-ehr to read' },
  { id: 37, spanish: 'Escribir', transliteration: 'es-kree-beer', meaning: 'To write', category: 'Verbs', mnemonic: 'ESCRIBIR - Es-kree-beer to write' },
  { id: 38, spanish: 'Comprar', transliteration: 'kohm-prahr', meaning: 'To buy', category: 'Verbs', mnemonic: 'COMPRAR - Kohm-prahr to buy' },
  { id: 39, spanish: 'Vender', transliteration: 'behn-dehr', meaning: 'To sell', category: 'Verbs', mnemonic: 'VENDER - Behn-dehr to sell' },
  { id: 40, spanish: 'Hacer', transliteration: 'ah-sehr', meaning: 'To make', category: 'Verbs', mnemonic: 'HACER - Ah-sehr to make' },
  { id: 41, spanish: 'Usar', transliteration: 'oo-sahr', meaning: 'To use', category: 'Verbs', mnemonic: 'USAR - Oo-sahr to use' },
  { id: 42, spanish: 'Saber', transliteration: 'sah-behr', meaning: 'To know', category: 'Verbs', mnemonic: 'SABER - Sah-behr to know' },
  { id: 43, spanish: 'Pensar', transliteration: 'pehn-sahr', meaning: 'To think', category: 'Verbs', mnemonic: 'PENSAR - Pehn-sahr to think' },
  { id: 44, spanish: 'Decir', transliteration: 'deh-seer', meaning: 'To say', category: 'Verbs', mnemonic: 'DECIR - Deh-seer to say' },
  { id: 45, spanish: 'Sostener', transliteration: 'sohs-teh-nehr', meaning: 'To hold / To carry', category: 'Verbs', mnemonic: 'SOSTENER - Sohs-teh-nehr to hold' },
  { id: 46, spanish: 'Estar de pie', transliteration: 'es-tahr deh pee-eh', meaning: 'To stand', category: 'Verbs', mnemonic: 'ESTAR DE PIE - Es-tahr deh pee-eh to stand' },
  { id: 47, spanish: 'Sentarse', transliteration: 'sehn-tahr-seh', meaning: 'To sit', category: 'Verbs', mnemonic: 'SENTARSE - Sehn-tahr-seh to sit' },
  { id: 48, spanish: 'Dormir', transliteration: 'dohr-meer', meaning: 'To sleep', category: 'Verbs', mnemonic: 'DORMIR - Dohr-meer to sleep' },
  { id: 49, spanish: 'Despertar', transliteration: 'des-pehr-tahr', meaning: 'To wake up', category: 'Verbs', mnemonic: 'DESPERTAR - Des-pehr-tahr to wake' },
  { id: 50, spanish: 'Caminar', transliteration: 'kah-mee-nahr', meaning: 'To walk', category: 'Verbs', mnemonic: 'CAMINAR - Kah-mee-nahr to walk' },
  { id: 51, spanish: 'Correr', transliteration: 'koh-rehr', meaning: 'To run', category: 'Verbs', mnemonic: 'CORRER - Koh-rehr to run' },
  { id: 52, spanish: 'Nadar', transliteration: 'nah-dahr', meaning: 'To swim', category: 'Verbs', mnemonic: 'NADAR - Nah-dahr to swim' },
  { id: 53, spanish: 'Volar', transliteration: 'boh-lahr', meaning: 'To fly', category: 'Verbs', mnemonic: 'VOLAR - Boh-lahr to fly' },
  { id: 54, spanish: 'Abrir', transliteration: 'ah-breer', meaning: 'To open', category: 'Verbs', mnemonic: 'ABRIR - Ah-breer to open' },
  { id: 55, spanish: 'Cerrar', transliteration: 'seh-rrahr', meaning: 'To close', category: 'Verbs', mnemonic: 'CERRAR - Seh-rrahr to close' },
  { id: 56, spanish: 'Entrar', transliteration: 'ehn-trahr', meaning: 'To enter', category: 'Verbs', mnemonic: 'ENTRAR - Ehn-trahr to enter' },
  { id: 57, spanish: 'Salir', transliteration: 'sah-leer', meaning: 'To exit', category: 'Verbs', mnemonic: 'SALIR - Sah-leer to exit' },
  { id: 58, spanish: 'Encontrar', transliteration: 'ehn-kohn-trahr', meaning: 'To meet', category: 'Verbs', mnemonic: 'ENCONTRAR - Ehn-kohn-trahr to meet' },
  { id: 59, spanish: 'Esperar', transliteration: 'es-peh-rahr', meaning: 'To wait', category: 'Verbs', mnemonic: 'ESPERAR - Es-peh-rahr to wait' },
  { id: 60, spanish: 'Volver', transliteration: 'bohl-behr', meaning: 'To return', category: 'Verbs', mnemonic: 'VOLVER - Bohl-behr to return' },
  { id: 61, spanish: 'Uno', transliteration: 'oo-noh', meaning: 'One', category: 'Numbers', mnemonic: 'UNO - Oo-noh is one' },
  { id: 62, spanish: 'Dos', transliteration: 'dohs', meaning: 'Two', category: 'Numbers', mnemonic: 'DOS - Dohs is two' },
  { id: 63, spanish: 'Tres', transliteration: 'trehs', meaning: 'Three', category: 'Numbers', mnemonic: 'TRES - Trehs is three' },
  { id: 64, spanish: 'Cuatro', transliteration: 'kwah-troh', meaning: 'Four', category: 'Numbers', mnemonic: 'CUATRO - Kwah-troh is four' },
  { id: 65, spanish: 'Cinco', transliteration: 'seen-koh', meaning: 'Five', category: 'Numbers', mnemonic: 'CINCO - Seen-koh is five' },
  { id: 66, spanish: 'Seis', transliteration: 'says', meaning: 'Six', category: 'Numbers', mnemonic: 'SEIS - Says is six' },
  { id: 67, spanish: 'Siete', transliteration: 'see-eh-teh', meaning: 'Seven', category: 'Numbers', mnemonic: 'SIETE - See-eh-teh is seven' },
  { id: 68, spanish: 'Ocho', transliteration: 'oh-choh', meaning: 'Eight', category: 'Numbers', mnemonic: 'OCHO - Oh-choh is eight' },
  { id: 69, spanish: 'Nueve', transliteration: 'nweh-beh', meaning: 'Nine', category: 'Numbers', mnemonic: 'NUEVE - Nweh-beh is nine' },
  { id: 70, spanish: 'Diez', transliteration: 'dee-ehs', meaning: 'Ten', category: 'Numbers', mnemonic: 'DIEZ - Dee-ehs is ten' },
  { id: 71, spanish: 'Cien', transliteration: 'see-ehn', meaning: 'Hundred', category: 'Numbers', mnemonic: 'CIEN - See-ehn is hundred' },
  { id: 72, spanish: 'Mil', transliteration: 'meel', meaning: 'Thousand', category: 'Numbers', mnemonic: 'MIL - Meel is thousand' },
  { id: 73, spanish: 'Rojo', transliteration: 'roh-hoh', meaning: 'Red', category: 'Adjectives', mnemonic: 'ROJO - Roh-hoh is red' },
  { id: 74, spanish: 'Azul', transliteration: 'ah-sool', meaning: 'Blue', category: 'Adjectives', mnemonic: 'AZUL - Ah-sool is blue' },
  { id: 75, spanish: 'Blanco', transliteration: 'blahn-koh', meaning: 'White', category: 'Adjectives', mnemonic: 'BLANCO - Blahn-koh is white' },
  { id: 76, spanish: 'Negro', transliteration: 'neh-groh', meaning: 'Black', category: 'Adjectives', mnemonic: 'NEGRO - Neh-groh is black' },
  { id: 77, spanish: 'Nuevo', transliteration: 'nweh-boh', meaning: 'New', category: 'Adjectives', mnemonic: 'NUEVO - Nweh-boh is new' },
  { id: 78, spanish: 'Viejo', transliteration: 'bee-eh-hoh', meaning: 'Old', category: 'Adjectives', mnemonic: 'VIEJO - Bee-eh-hoh is old' },
  { id: 79, spanish: 'Bueno', transliteration: 'bweh-noh', meaning: 'Good', category: 'Adjectives', mnemonic: 'BUENO - Bweh-noh is good' },
  { id: 80, spanish: 'Malo', transliteration: 'mah-loh', meaning: 'Bad', category: 'Adjectives', mnemonic: 'MALO - Mah-loh is bad' },
  { id: 81, spanish: 'Alto', transliteration: 'ahl-toh', meaning: 'High', category: 'Adjectives', mnemonic: 'ALTO - Ahl-toh is high' },
  { id: 82, spanish: 'Barato', transliteration: 'bah-rah-toh', meaning: 'Cheap', category: 'Adjectives', mnemonic: 'BARATO - Bah-rah-toh is cheap' },
  { id: 83, spanish: 'Largo', transliteration: 'lahr-goh', meaning: 'Long / Tall', category: 'Adjectives', mnemonic: 'LARGO - Lahr-goh is long' },
  { id: 84, spanish: 'Corto', transliteration: 'kohr-toh', meaning: 'Short', category: 'Adjectives', mnemonic: 'CORTO - Kohr-toh is short' },
  { id: 85, spanish: 'Mucho', transliteration: 'moo-choh', meaning: 'Many / Much', category: 'Adjectives', mnemonic: 'MUCHO - Moo-choh is many' },
  { id: 86, spanish: 'Poco', transliteration: 'poh-koh', meaning: 'Few / Little', category: 'Adjectives', mnemonic: 'POCO - Poh-koh is few' },
  { id: 87, spanish: 'Caliente', transliteration: 'kah-lee-ehn-teh', meaning: 'Hot', category: 'Adjectives', mnemonic: 'CALIENTE - Kah-lee-ehn-teh is hot' },
  { id: 88, spanish: 'Frío', transliteration: 'free-oh', meaning: 'Cold', category: 'Adjectives', mnemonic: 'FRÍO - Free-oh is cold' },
  { id: 89, spanish: 'Tibio', transliteration: 'tee-bee-oh', meaning: 'Warm', category: 'Adjectives', mnemonic: 'TIBIO - Tee-bee-oh is warm' },
  { id: 90, spanish: 'Fresco', transliteration: 'frehs-koh', meaning: 'Cool', category: 'Adjectives', mnemonic: 'FRESCO - Frehs-koh is cool' },
  { id: 91, spanish: 'Difícil', transliteration: 'dee-fee-seel', meaning: 'Difficult', category: 'Adjectives', mnemonic: 'DIFÍCIL - Dee-fee-seel is difficult' },
  { id: 92, spanish: 'Fácil', transliteration: 'fah-seel', meaning: 'Easy', category: 'Adjectives', mnemonic: 'FÁCIL - Fah-seel is easy' },
  { id: 93, spanish: 'Divertido', transliteration: 'dee-behr-tee-doh', meaning: 'Fun / Enjoyable', category: 'Adjectives', mnemonic: 'DIVERTIDO - Dee-behr-tee-doh is fun' },
  { id: 94, spanish: 'Feliz', transliteration: 'feh-lees', meaning: 'Happy', category: 'Adjectives', mnemonic: 'FELIZ - Feh-lees is happy' },
  { id: 95, spanish: 'Triste', transliteration: 'trees-teh', meaning: 'Sad', category: 'Adjectives', mnemonic: 'TRISTE - Trees-teh is sad' },
  { id: 96, spanish: 'Asustador', transliteration: 'ah-soos-tah-dohr', meaning: 'Scary', category: 'Adjectives', mnemonic: 'ASUSTADOR - Ah-soos-tah-dohr is scary' },
  { id: 97, spanish: 'Fuerte', transliteration: 'fwehr-teh', meaning: 'Strong', category: 'Adjectives', mnemonic: 'FUERTE - Fwehr-teh is strong' },
  { id: 98, spanish: 'Débil', transliteration: 'deh-beel', meaning: 'Weak', category: 'Adjectives', mnemonic: 'DÉBIL - Deh-beel is weak' },
  { id: 99, spanish: 'Rápido', transliteration: 'rah-pee-doh', meaning: 'Fast', category: 'Adjectives', mnemonic: 'RÁPIDO - Rah-pee-doh is fast' },
  { id: 100, spanish: 'Lento', transliteration: 'lehn-toh', meaning: 'Slow', category: 'Adjectives', mnemonic: 'LENTO - Lehn-toh is slow' },
];

export const TOTAL_VOCAB = [
  ...VOCABULARY_DATA,
  ...EXTENDED_VOCABULARY,
  ...VOCAB_201_300,
  ...VOCAB_301_400,
  ...VOCAB_401_500
];
