import { Word } from './types';

export const VOCAB_201_300: Word[] = [
  { id: 201, spanish: 'Romper', transliteration: 'rohm-pehr', meaning: 'To break', category: 'Verbs', mnemonic: 'ROMPER - Rohm-pehr to break' },
  { id: 202, spanish: 'Caer', transliteration: 'kah-ehr', meaning: 'To fall', category: 'Verbs', mnemonic: 'CAER - Kah-ehr to fall' },
  { id: 203, spanish: 'Levantar', transliteration: 'leh-bahn-tahr', meaning: 'To raise', category: 'Verbs', mnemonic: 'LEVANTAR - Leh-bahn-tahr to raise' },
  { id: 204, spanish: 'Bajar', transliteration: 'bah-hahr', meaning: 'To lower', category: 'Verbs', mnemonic: 'BAJAR - Bah-hahr to lower' },
  { id: 205, spanish: 'Empujar', transliteration: 'ehm-poo-hahr', meaning: 'To push', category: 'Verbs', mnemonic: 'EMPUJAR - Ehm-poo-hahr to push' },
  { id: 206, spanish: 'Jalar', transliteration: 'hah-lahr', meaning: 'To pull', category: 'Verbs', mnemonic: 'JALAR - Hah-lahr to pull' },
  { id: 207, spanish: 'Tirar', transliteration: 'tee-rahr', meaning: 'To throw', category: 'Verbs', mnemonic: 'TIRAR - Tee-rahr to throw' },
  { id: 208, spanish: 'Tomar', transliteration: 'toh-mahr', meaning: 'To take', category: 'Verbs', mnemonic: 'TOMAR - Toh-mahr to take' },
  { id: 209, spanish: 'Poner', transliteration: 'poh-nehr', meaning: 'To put', category: 'Verbs', mnemonic: 'PONER - Poh-nehr to put' },
  { id: 210, spanish: 'Hacer fila', transliteration: 'ah-sehr fee-lah', meaning: 'To line up', category: 'Verbs', mnemonic: 'HACER FILA - Ah-sehr fee-lah to line up' },
  { id: 211, spanish: 'Coleccionar', transliteration: 'koh-lehk-see-oh-nahr', meaning: 'To collect', category: 'Verbs', mnemonic: 'COLECCIONAR - Koh-lehk-see-oh-nahr to collect' },
  { id: 212, spanish: 'Dividir', transliteration: 'dee-bee-deer', meaning: 'To divide', category: 'Verbs', mnemonic: 'DIVIDIR - Dee-bee-deer to divide' },
  { id: 213, spanish: 'Mezclar', transliteration: 'mehs-klahr', meaning: 'To mix', category: 'Verbs', mnemonic: 'MEZCLAR - Mehs-klahr to mix' },
  { id: 214, spanish: 'Aumentar', transliteration: 'ow-mehn-tahr', meaning: 'To increase', category: 'Verbs', mnemonic: 'AUMENTAR - Ow-mehn-tahr to increase' },
  { id: 215, spanish: 'Disminuir', transliteration: 'dees-mee-noo-eer', meaning: 'To decrease', category: 'Verbs', mnemonic: 'DISMINUIR - Dees-mee-noo-eer to decrease' },
  { id: 216, spanish: 'Continuar', transliteration: 'kohn-tee-noo-ahr', meaning: 'To continue', category: 'Verbs', mnemonic: 'CONTINUAR - Kohn-tee-noo-ahr to continue' },
  { id: 217, spanish: 'Parar', transliteration: 'pah-rahr', meaning: 'To stop', category: 'Verbs', mnemonic: 'PARAR - Pah-rahr to stop' },
  { id: 218, spanish: 'Mover', transliteration: 'moh-behr', meaning: 'To move', category: 'Verbs', mnemonic: 'MOVER - Moh-behr to move' },
  { id: 219, spanish: 'Girar', transliteration: 'hee-rahr', meaning: 'To turn', category: 'Verbs', mnemonic: 'GIRAR - Hee-rahr to turn' },
  { id: 220, spanish: 'Doblar', transliteration: 'doh-blahr', meaning: 'To bend', category: 'Verbs', mnemonic: 'DOBLAR - Doh-blahr to bend' },
  { id: 221, spanish: 'Cruzar', transliteration: 'kroo-sahr', meaning: 'To cross', category: 'Verbs', mnemonic: 'CRUZAR - Kroo-sahr to cross' },
  { id: 222, spanish: 'Pasar', transliteration: 'pah-sahr', meaning: 'To pass', category: 'Verbs', mnemonic: 'PASAR - Pah-sahr to pass' },
  { id: 223, spanish: 'Montar', transliteration: 'mohn-tahr', meaning: 'To ride', category: 'Verbs', mnemonic: 'MONTAR - Mohn-tahr to ride' },
  { id: 224, spanish: 'Bajarse', transliteration: 'bah-hahr-seh', meaning: 'To get off', category: 'Verbs', mnemonic: 'BAJARSE - Bah-hahr-seh to get off' },
  { id: 225, spanish: 'Conducir', transliteration: 'kohn-doo-seer', meaning: 'To drive', category: 'Verbs', mnemonic: 'CONDUCIR - Kohn-doo-seer to drive' },
  { id: 226, spanish: 'Detener', transliteration: 'deh-teh-nehr', meaning: 'To stop something', category: 'Verbs', mnemonic: 'DETENER - Deh-teh-nehr to stop' },
  { id: 227, spanish: 'Apurarse', transliteration: 'ah-poo-rahr-seh', meaning: 'To hurry', category: 'Verbs', mnemonic: 'APURARSE - Ah-poo-rahr-seh to hurry' },
  { id: 228, spanish: 'Llegar tarde', transliteration: 'yeh-gahr tahr-deh', meaning: 'To be late', category: 'Verbs', mnemonic: 'LLEGAR TARDE - Yeh-gahr tahr-deh to be late' },
  { id: 229, spanish: 'Alcanzar', transliteration: 'ahl-kahn-sahr', meaning: 'To catch up', category: 'Verbs', mnemonic: 'ALCANZAR - Ahl-kahn-sahr to catch up' },
  { id: 230, spanish: 'Promesa', transliteration: 'proh-meh-sah', meaning: 'Promise', category: 'Verbs', mnemonic: 'PROMESA - Proh-meh-sah is promise' },
  { id: 231, spanish: 'Pedir', transliteration: 'peh-deer', meaning: 'To request', category: 'Verbs', mnemonic: 'PEDIR - Peh-deer to request' },
  { id: 232, spanish: 'Ayudar', transliteration: 'ah-yoo-dahr', meaning: 'To help', category: 'Verbs', mnemonic: 'AYUDAR - Ah-yoo-dahr to help' },
  { id: 233, spanish: 'Cansado', transliteration: 'kahn-sah-doh', meaning: 'To be tired', category: 'Verbs', mnemonic: 'CANSADO - Kahn-sah-doh is tired' },
  { id: 234, spanish: 'Contento', transliteration: 'kohn-tehn-toh', meaning: 'To be glad', category: 'Verbs', mnemonic: 'CONTENTO - Kohn-tehn-toh is glad' },
  { id: 235, spanish: 'Enojado', transliteration: 'eh-noh-hah-doh', meaning: 'To be angry', category: 'Verbs', mnemonic: 'ENOJADO - Eh-noh-hah-doh is angry' },
  { id: 236, spanish: 'Sorprendido', transliteration: 'sohr-prehn-dee-doh', meaning: 'To be surprised', category: 'Verbs', mnemonic: 'SORPRENDIDO - Sohr-prehn-dee-doh is surprised' },
  { id: 237, spanish: 'Preocupado', transliteration: 'preh-oh-koo-pah-doh', meaning: 'Worry', category: 'Adjectives', mnemonic: 'PREOCUPADO - Preh-oh-koo-pah-doh is worried' },
  { id: 238, spanish: 'Tranquilo', transliteration: 'trahn-kee-loh', meaning: 'Relief', category: 'Adjectives', mnemonic: 'TRANQUILO - Trahn-kee-loh is calm' },
  { id: 239, spanish: 'Lamentable', transliteration: 'lah-mehn-tah-bleh', meaning: 'Regrettable', category: 'Adjectives', mnemonic: 'LAMENTABLE - Lah-mehn-tah-bleh is regrettable' },
  { id: 240, spanish: 'Importante', transliteration: 'eem-pohr-tahn-teh', meaning: 'Important', category: 'Adjectives', mnemonic: 'IMPORTANTE - Eem-pohr-tahn-teh is important' },
  { id: 241, spanish: 'Conveniente', transliteration: 'kohn-beh-nee-ehn-teh', meaning: 'Convenient', category: 'Adjectives', mnemonic: 'CONVENIENTE - Kohn-beh-nee-ehn-teh is convenient' },
  { id: 242, spanish: 'Inconveniente', transliteration: 'een-kohn-beh-nee-ehn-teh', meaning: 'Inconvenient', category: 'Adjectives', mnemonic: 'INCONVENIENTE - Een-kohn-beh-nee-ehn-teh is inconvenient' },
  { id: 243, spanish: 'Simple', transliteration: 'seem-pleh', meaning: 'Simple', category: 'Adjectives', mnemonic: 'SIMPLE - Seem-pleh is simple' },
  { id: 244, spanish: 'Complicado', transliteration: 'kohm-plee-kah-doh', meaning: 'Complicated', category: 'Adjectives', mnemonic: 'COMPLICADO - Kohm-plee-kah-doh is complicated' },
  { id: 245, spanish: 'Tranquilo', transliteration: 'trahn-kee-loh', meaning: 'Quiet', category: 'Adjectives', mnemonic: 'TRANQUILO - Trahn-kee-loh is quiet' },
  { id: 246, spanish: 'Ruidoso', transliteration: 'roo-ee-doh-soh', meaning: 'Noisy', category: 'Adjectives', mnemonic: 'RUIDOSO - Roo-ee-doh-soh is noisy' },
  { id: 247, spanish: 'Hermoso', transliteration: 'ehr-moh-soh', meaning: 'Beautiful', category: 'Adjectives', mnemonic: 'HERMOSO - Ehr-moh-soh is beautiful' },
  { id: 248, spanish: 'Sucio', transliteration: 'soo-see-oh', meaning: 'Dirty', category: 'Adjectives', mnemonic: 'SUCIO - Soo-see-oh is dirty' },
  { id: 249, spanish: 'Famoso', transliteration: 'fah-moh-soh', meaning: 'Famous', category: 'Adjectives', mnemonic: 'FAMOSO - Fah-moh-soh is famous' },
  { id: 250, spanish: 'Especial', transliteration: 'es-peh-see-ahl', meaning: 'Special', category: 'Adjectives', mnemonic: 'ESPECIAL - Es-peh-see-ahl is special' },
  { id: 251, spanish: 'Normal', transliteration: 'nohr-mahl', meaning: 'Normal', category: 'Adjectives', mnemonic: 'NORMAL - Nohr-mahl is normal' },
  { id: 252, spanish: 'Igual', transliteration: 'ee-gwahl', meaning: 'Same', category: 'Adjectives', mnemonic: 'IGUAL - Ee-gwahl is same' },
  { id: 253, spanish: 'Diferente', transliteration: 'dee-feh-rehn-teh', meaning: 'Different', category: 'Adjectives', mnemonic: 'DIFERENTE - Dee-feh-rehn-teh is different' },
  { id: 254, spanish: 'Correcto', transliteration: 'koh-rrehk-toh', meaning: 'Correct', category: 'Adjectives', mnemonic: 'CORRECTO - Koh-rrehk-toh is correct' },
  { id: 255, spanish: 'Error', transliteration: 'eh-rrohr', meaning: 'Mistake', category: 'Adjectives', mnemonic: 'ERROR - Eh-rrohr is mistake' },
  { id: 256, spanish: 'Peligroso', transliteration: 'peh-lee-groh-soh', meaning: 'Dangerous', category: 'Adjectives', mnemonic: 'PELIGROSO - Peh-lee-groh-soh is dangerous' },
  { id: 257, spanish: 'Seguro', transliteration: 'seh-goo-roh', meaning: 'Safe', category: 'Adjectives', mnemonic: 'SEGURO - Seh-goo-roh is safe' },
  { id: 258, spanish: 'Enérgico', transliteration: 'eh-nehr-hee-koh', meaning: 'Energetic', category: 'Adjectives', mnemonic: 'ENÉRGICO - Eh-nehr-hee-koh is energetic' },
  { id: 259, spanish: 'Enfermo', transliteration: 'ehn-fehr-moh', meaning: 'Sick', category: 'Adjectives', mnemonic: 'ENFERMO - Ehn-fehr-moh is sick' },
  { id: 260, spanish: 'Doloroso', transliteration: 'doh-loh-roh-soh', meaning: 'Painful', category: 'Adjectives', mnemonic: 'DOLOROSO - Doh-loh-roh-soh is painful' },
  { id: 261, spanish: 'Grueso', transliteration: 'groo-eh-soh', meaning: 'Thick', category: 'Adjectives', mnemonic: 'GRUESO - Groo-eh-soh is thick' },
  { id: 262, spanish: 'Delgado', transliteration: 'dehl-gah-doh', meaning: 'Thin', category: 'Adjectives', mnemonic: 'DELGADO - Dehl-gah-doh is thin' },
  { id: 263, spanish: 'Ancho', transliteration: 'ahn-choh', meaning: 'Wide', category: 'Adjectives', mnemonic: 'ANCHO - Ahn-choh is wide' },
  { id: 264, spanish: 'Estrecho', transliteration: 'es-treh-choh', meaning: 'Narrow', category: 'Adjectives', mnemonic: 'ESTRECHO - Es-treh-choh is narrow' },
  { id: 265, spanish: 'Profundo', transliteration: 'proh-foon-doh', meaning: 'Deep', category: 'Adjectives', mnemonic: 'PROFUNDO - Proh-foon-doh is deep' },
  { id: 266, spanish: 'Superficial', transliteration: 'soo-pehr-fee-see-ahl', meaning: 'Shallow', category: 'Adjectives', mnemonic: 'SUPERFICIAL - Soo-pehr-fee-see-ahl is shallow' },
  { id: 267, spanish: 'Pesado', transliteration: 'peh-sah-doh', meaning: 'Heavy', category: 'Adjectives', mnemonic: 'PESADO - Peh-sah-doh is heavy' },
  { id: 268, spanish: 'Ligero', transliteration: 'lee-heh-roh', meaning: 'Light', category: 'Adjectives', mnemonic: 'LIGERO - Lee-heh-roh is light' },
  { id: 269, spanish: 'Duro', transliteration: 'doo-roh', meaning: 'Hard', category: 'Adjectives', mnemonic: 'DURO - Doo-roh is hard' },
  { id: 270, spanish: 'Suave', transliteration: 'swah-beh', meaning: 'Soft', category: 'Adjectives', mnemonic: 'SUAVE - Swah-beh is soft' },
  { id: 271, spanish: 'Redondo', transliteration: 'reh-dohn-doh', meaning: 'Round', category: 'Adjectives', mnemonic: 'REDONDO - Reh-dohn-doh is round' },
  { id: 272, spanish: 'Cuadrado', transliteration: 'kwah-drah-doh', meaning: 'Square', category: 'Adjectives', mnemonic: 'CUADRADO - Kwah-drah-doh is square' },
  { id: 273, spanish: 'Plano', transliteration: 'plah-noh', meaning: 'Flat', category: 'Adjectives', mnemonic: 'PLANO - Plah-noh is flat' },
  { id: 274, spanish: 'Recto', transliteration: 'rrehk-toh', meaning: 'Straight', category: 'Adjectives', mnemonic: 'RECTO - Rrehk-toh is straight' },
  { id: 275, spanish: 'Cerca', transliteration: 'sehr-kah', meaning: 'Near', category: 'Adjectives', mnemonic: 'CERCA - Sehr-kah is near' },
  { id: 276, spanish: 'Lejos', transliteration: 'leh-hohs', meaning: 'Far', category: 'Adjectives', mnemonic: 'LEJOS - Leh-hohs is far' },
  { id: 277, spanish: 'Joven', transliteration: 'hoh-behn', meaning: 'Young', category: 'Adjectives', mnemonic: 'JOVEN - Hoh-behn is young' },
  { id: 278, spanish: 'Anciano', transliteration: 'ahn-see-ah-noh', meaning: 'Old', category: 'Adjectives', mnemonic: 'ANCIANO - Ahn-see-ah-noh is old' },
  { id: 279, spanish: 'Brillante', transliteration: 'bree-yahn-teh', meaning: 'Bright', category: 'Adjectives', mnemonic: 'BRILLANTE - Bree-yahn-teh is bright' },
  { id: 280, spanish: 'Oscuro', transliteration: 'ohs-koo-roh', meaning: 'Dark', category: 'Adjectives', mnemonic: 'OSCURO - Ohs-koo-roh is dark' },
  { id: 281, spanish: 'Espeso', transliteration: 'es-peh-soh', meaning: 'Thick', category: 'Adjectives', mnemonic: 'ESPESO - Es-peh-soh is thick' },
  { id: 282, spanish: 'Ligero', transliteration: 'lee-heh-roh', meaning: 'Thin', category: 'Adjectives', mnemonic: 'LIGERO - Lee-heh-roh is thin' },
  { id: 283, spanish: 'Dulce', transliteration: 'dool-seh', meaning: 'Sweet', category: 'Adjectives', mnemonic: 'DULCE - Dool-seh is sweet' },
  { id: 284, spanish: 'Picante', transliteration: 'pee-kahn-teh', meaning: 'Spicy', category: 'Adjectives', mnemonic: 'PICANTE - Pee-kahn-teh is spicy' },
  { id: 285, spanish: 'Amargo', transliteration: 'ah-mahr-goh', meaning: 'Bitter', category: 'Adjectives', mnemonic: 'AMARGO - Ah-mahr-goh is bitter' },
  { id: 286, spanish: 'Ácido', transliteration: 'ah-see-doh', meaning: 'Sour', category: 'Adjectives', mnemonic: 'ÁCIDO - Ah-see-doh is sour' },
  { id: 287, spanish: 'Salado', transliteration: 'sah-lah-doh', meaning: 'Salty', category: 'Adjectives', mnemonic: 'SALADO - Sah-lah-doh is salty' },
  { id: 288, spanish: 'Fragante', transliteration: 'frah-gahn-teh', meaning: 'Fragrant', category: 'Adjectives', mnemonic: 'FRAGANTE - Frah-gahn-teh is fragrant' },
  { id: 289, spanish: 'Apestoso', transliteration: 'ah-pes-toh-soh', meaning: 'Smelly', category: 'Adjectives', mnemonic: 'APESTOSO - Ah-pes-toh-soh is smelly' },
  { id: 290, spanish: 'Buen olor', transliteration: 'bwehn oh-lohr', meaning: 'Good smell', category: 'Adjectives', mnemonic: 'BUEN OLOR - Bwehn oh-lohr is good smell' },
  { id: 291, spanish: 'Molesto', transliteration: 'moh-les-toh', meaning: 'Annoying', category: 'Adjectives', mnemonic: 'MOLESTO - Moh-les-toh is annoying' },
  { id: 292, spanish: 'Inteligente', transliteration: 'een-teh-lee-hehn-teh', meaning: 'Smart', category: 'Adjectives', mnemonic: 'INTELIGENTE - Een-teh-lee-hehn-teh is smart' },
  { id: 293, spanish: 'Tonto', transliteration: 'tohn-toh', meaning: 'Stupid', category: 'Adjectives', mnemonic: 'TONTO - Tohn-toh is stupid' },
  { id: 294, spanish: 'Amable', transliteration: 'ah-mah-bleh', meaning: 'Kind', category: 'Adjectives', mnemonic: 'AMABLE - Ah-mah-bleh is kind' },
  { id: 295, spanish: 'Estricto', transliteration: 'es-treek-toh', meaning: 'Strict', category: 'Adjectives', mnemonic: 'ESTRICTO - Es-treek-toh is strict' },
  { id: 296, spanish: 'Ocupado', transliteration: 'oh-koo-pah-doh', meaning: 'Busy', category: 'Adjectives', mnemonic: 'OCUPADO - Oh-koo-pah-doh is busy' },
  { id: 297, spanish: 'Libre', transliteration: 'lee-breh', meaning: 'Free time', category: 'Adjectives', mnemonic: 'LIBRE - Lee-breh is free' },
  { id: 298, spanish: 'Interesante', transliteration: 'een-teh-reh-sahn-teh', meaning: 'Interesting', category: 'Adjectives', mnemonic: 'INTERESANTE - Een-teh-reh-sahn-teh is interesting' },
  { id: 299, spanish: 'Aburrido', transliteration: 'ah-boo-rree-doh', meaning: 'Boring', category: 'Adjectives', mnemonic: 'ABURRIDO - Ah-boo-rree-doh is boring' },
  { id: 300, spanish: 'Maravilloso', transliteration: 'mah-rah-bee-yoh-soh', meaning: 'Wonderful', category: 'Adjectives', mnemonic: 'MARAVILLOSO - Mah-rah-bee-yoh-soh is wonderful' },
];
