import { Word } from './types';

export const EXTENDED_VOCABULARY: Word[] = [
  { id: 101, spanish: 'Persona', transliteration: 'pehr-soh-nah', meaning: 'Person', category: 'People', mnemonic: 'PERSONA - Pehr-soh-nah is person' },
  { id: 102, spanish: 'Hombre', transliteration: 'ohm-breh', meaning: 'Man', category: 'People', mnemonic: 'HOMBRE - Ohm-breh is man' },
  { id: 103, spanish: 'Mujer', transliteration: 'moo-hehr', meaning: 'Woman', category: 'People', mnemonic: 'MUJER - Moo-hehr is woman' },
  { id: 104, spanish: 'Niño', transliteration: 'nee-nyoh', meaning: 'Child', category: 'People', mnemonic: 'NIÑO - Nee-nyoh is child' },
  { id: 105, spanish: 'Madre', transliteration: 'mah-dreh', meaning: 'Mother', category: 'People', mnemonic: 'MADRE - Mah-dreh is mother' },
  { id: 106, spanish: 'Padre', transliteration: 'pah-dreh', meaning: 'Father', category: 'People', mnemonic: 'PADRE - Pah-dreh is father' },
  { id: 107, spanish: 'Hermano', transliteration: 'ehr-mah-noh', meaning: 'Brother', category: 'People', mnemonic: 'HERMANO - Ehr-mah-noh is brother' },
  { id: 108, spanish: 'Hermana', transliteration: 'ehr-mah-nah', meaning: 'Sister', category: 'People', mnemonic: 'HERMANA - Ehr-mah-nah is sister' },
  { id: 109, spanish: 'Hijo', transliteration: 'ee-hoh', meaning: 'Son', category: 'People', mnemonic: 'HIJO - Ee-hoh is son' },
  { id: 110, spanish: 'Hija', transliteration: 'ee-hah', meaning: 'Daughter', category: 'People', mnemonic: 'HIJA - Ee-hah is daughter' },
  { id: 111, spanish: 'Tiempo', transliteration: 'tee-ehm-poh', meaning: 'Time', category: 'Time', mnemonic: 'TIEMPO - Tee-ehm-poh is time' },
  { id: 112, spanish: 'Mañana', transliteration: 'mah-nyah-nah', meaning: 'Morning', category: 'Time', mnemonic: 'MAÑANA - Mah-nyah-nah is morning' },
  { id: 113, spanish: 'Mediodía', transliteration: 'meh-dee-oh-dee-ah', meaning: 'Noon', category: 'Time', mnemonic: 'MEDIODÍA - Meh-dee-oh-dee-ah is noon' },
  { id: 114, spanish: 'Noche', transliteration: 'noh-cheh', meaning: 'Night', category: 'Time', mnemonic: 'NOCHE - Noh-cheh is night' },
  { id: 115, spanish: 'Semana', transliteration: 'seh-mah-nah', meaning: 'Week', category: 'Time', mnemonic: 'SEMANA - Seh-mah-nah is week' },
  { id: 116, spanish: 'Año', transliteration: 'ah-nyoh', meaning: 'Year', category: 'Time', mnemonic: 'AÑO - Ah-nyoh is year' },
  { id: 117, spanish: 'Primavera', transliteration: 'pree-mah-beh-rah', meaning: 'Spring', category: 'Time', mnemonic: 'PRIMAVERA - Pree-mah-beh-rah is spring' },
  { id: 118, spanish: 'Verano', transliteration: 'beh-rah-noh', meaning: 'Summer', category: 'Time', mnemonic: 'VERANO - Beh-rah-noh is summer' },
  { id: 119, spanish: 'Otoño', transliteration: 'oh-toh-nyoh', meaning: 'Autumn', category: 'Time', mnemonic: 'OTOÑO - Oh-toh-nyoh is autumn' },
  { id: 120, spanish: 'Invierno', transliteration: 'een-bee-ehr-noh', meaning: 'Winter', category: 'Time', mnemonic: 'INVIERNO - Een-bee-ehr-noh is winter' },
  { id: 121, spanish: 'Clima', transliteration: 'klee-mah', meaning: 'Weather', category: 'Nature', mnemonic: 'CLIMA - Klee-mah is weather' },
  { id: 122, spanish: 'Lluvia', transliteration: 'yoo-bee-ah', meaning: 'Rain', category: 'Nature', mnemonic: 'LLUVIA - Yoo-bee-ah is rain' },
  { id: 123, spanish: 'Nieve', transliteration: 'nee-eh-beh', meaning: 'Snow', category: 'Nature', mnemonic: 'NIEVE - Nee-eh-beh is snow' },
  { id: 124, spanish: 'Viento', transliteration: 'bee-ehn-toh', meaning: 'Wind', category: 'Nature', mnemonic: 'VIENTO - Bee-ehn-toh is wind' },
  { id: 125, spanish: 'Cielo', transliteration: 'see-eh-loh', meaning: 'Sky', category: 'Nature', mnemonic: 'CIELO - See-eh-loh is sky' },
  { id: 126, spanish: 'Mar', transliteration: 'mahr', meaning: 'Sea', category: 'Nature', mnemonic: 'MAR - Mahr is sea' },
  { id: 127, spanish: 'Montaña', transliteration: 'mohn-tah-nyah', meaning: 'Mountain', category: 'Nature', mnemonic: 'MONTAÑA - Mohn-tah-nyah is mountain' },
  { id: 128, spanish: 'Río', transliteration: 'ree-oh', meaning: 'River', category: 'Nature', mnemonic: 'RÍO - Ree-oh is river' },
  { id: 129, spanish: 'Árbol', transliteration: 'ahr-bohl', meaning: 'Tree', category: 'Nature', mnemonic: 'ÁRBOL - Ahr-bohl is tree' },
  { id: 130, spanish: 'Flor', transliteration: 'flohr', meaning: 'Flower', category: 'Nature', mnemonic: 'FLOR - Flohr is flower' },
  { id: 131, spanish: 'Pájaro', transliteration: 'pah-hah-roh', meaning: 'Bird', category: 'Nature', mnemonic: 'PÁJARO - Pah-hah-roh is bird' },
  { id: 132, spanish: 'Pez', transliteration: 'pehs', meaning: 'Fish', category: 'Nature', mnemonic: 'PEZ - Pehs is fish' },
  { id: 133, spanish: 'Carne', transliteration: 'kahr-neh', meaning: 'Meat', category: 'Objects', mnemonic: 'CARNE - Kahr-neh is meat' },
  { id: 134, spanish: 'Arroz', transliteration: 'ah-rohs', meaning: 'Rice', category: 'Objects', mnemonic: 'ARROZ - Ah-rohs is rice' },
  { id: 135, spanish: 'Pan', transliteration: 'pahn', meaning: 'Bread', category: 'Objects', mnemonic: 'PAN - Pahn is bread' },
  { id: 136, spanish: 'Huevo', transliteration: 'weh-boh', meaning: 'Egg', category: 'Objects', mnemonic: 'HUEVO - Weh-boh is egg' },
  { id: 137, spanish: 'Verduras', transliteration: 'behr-doo-rahs', meaning: 'Vegetables', category: 'Objects', mnemonic: 'VERDURAS - Behr-doo-rahs is vegetables' },
  { id: 138, spanish: 'Fruta', transliteration: 'froo-tah', meaning: 'Fruit', category: 'Objects', mnemonic: 'FRUTA - Froo-tah is fruit' },
  { id: 139, spanish: 'Té', transliteration: 'teh', meaning: 'Tea', category: 'Objects', mnemonic: 'TÉ - Teh is tea' },
  { id: 140, spanish: 'Café', transliteration: 'kah-feh', meaning: 'Coffee', category: 'Objects', mnemonic: 'CAFÉ - Kah-feh is coffee' },
  { id: 141, spanish: 'Leche', transliteration: 'leh-cheh', meaning: 'Milk', category: 'Objects', mnemonic: 'LECHE - Leh-cheh is milk' },
  { id: 142, spanish: 'Tienda', transliteration: 'tee-ehn-dah', meaning: 'Shop', category: 'Objects', mnemonic: 'TIENDA - Tee-ehn-dah is shop' },
  { id: 143, spanish: 'Restaurante', transliteration: 'reh-stow-rahn-teh', meaning: 'Restaurant', category: 'Objects', mnemonic: 'RESTAURANTE - Reh-stow-rahn-teh is restaurant' },
  { id: 144, spanish: 'Banco', transliteration: 'bahn-koh', meaning: 'Bank', category: 'Objects', mnemonic: 'BANCO - Bahn-koh is bank' },
  { id: 145, spanish: 'Hospital', transliteration: 'ohs-pee-tahl', meaning: 'Hospital', category: 'Objects', mnemonic: 'HOSPITAL - Ohs-pee-tahl is hospital' },
  { id: 146, spanish: 'Estación', transliteration: 'es-tah-see-ohn', meaning: 'Station', category: 'Objects', mnemonic: 'ESTACIÓN - Es-tah-see-ohn is station' },
  { id: 147, spanish: 'Aeropuerto', transliteration: 'ah-eh-roh-pwehr-toh', meaning: 'Airport', category: 'Objects', mnemonic: 'AEROPUERTO - Ah-eh-roh-pwehr-toh is airport' },
  { id: 148, spanish: 'Hotel', transliteration: 'oh-tehl', meaning: 'Hotel', category: 'Objects', mnemonic: 'HOTEL - Oh-tehl is hotel' },
  { id: 149, spanish: 'Habitación', transliteration: 'ah-bee-tah-see-ohn', meaning: 'Room', category: 'Objects', mnemonic: 'HABITACIÓN - Ah-bee-tah-see-ohn is room' },
  { id: 150, spanish: 'Oficina', transliteration: 'oh-fee-see-nah', meaning: 'Desk / Office', category: 'Objects', mnemonic: 'OFICINA - Oh-fee-see-nah is office' },
  { id: 151, spanish: 'Silla', transliteration: 'see-yah', meaning: 'Chair', category: 'Objects', mnemonic: 'SILLA - See-yah is chair' },
  { id: 152, spanish: 'Puerta', transliteration: 'pwehr-tah', meaning: 'Door', category: 'Objects', mnemonic: 'PUERTA - Pwehr-tah is door' },
  { id: 153, spanish: 'Ventana', transliteration: 'behn-tah-nah', meaning: 'Window', category: 'Objects', mnemonic: 'VENTANA - Behn-tah-nah is window' },
  { id: 154, spanish: 'Televisión', transliteration: 'teh-leh-bee-see-ohn', meaning: 'Television', category: 'Objects', mnemonic: 'TELEVISIÓN - Teh-leh-bee-see-ohn is TV' },
  { id: 155, spanish: 'Radio', transliteration: 'rah-dee-oh', meaning: 'Radio', category: 'Objects', mnemonic: 'RADIO - Rah-dee-oh is radio' },
  { id: 156, spanish: 'Teléfono', transliteration: 'teh-leh-foh-noh', meaning: 'Telephone', category: 'Objects', mnemonic: 'TELÉFONO - Teh-leh-foh-noh is phone' },
  { id: 157, spanish: 'Computadora', transliteration: 'kohm-poo-tah-doh-rah', meaning: 'Computer', category: 'Objects', mnemonic: 'COMPUTADORA - Kohm-poo-tah-doh-rah is computer' },
  { id: 158, spanish: 'Reloj', transliteration: 'reh-loh', meaning: 'Clock / Watch', category: 'Objects', mnemonic: 'RELOJ - Reh-loh is clock' },
  { id: 159, spanish: 'Cámara', transliteration: 'kah-mah-rah', meaning: 'Camera', category: 'Objects', mnemonic: 'CÁMARA - Kah-mah-rah is camera' },
  { id: 160, spanish: 'Foto', transliteration: 'foh-toh', meaning: 'Picture', category: 'Objects', mnemonic: 'FOTO - Foh-toh is picture' },
  { id: 161, spanish: 'Música', transliteration: 'moo-see-kah', meaning: 'Music', category: 'Objects', mnemonic: 'MÚSICA - Moo-see-kah is music' },
  { id: 162, spanish: 'Película', transliteration: 'peh-lee-koo-lah', meaning: 'Movie / Film', category: 'Objects', mnemonic: 'PELÍCULA - Peh-lee-koo-lah is movie' },
  { id: 163, spanish: 'Deportes', transliteration: 'deh-pohr-tehs', meaning: 'Sports', category: 'Objects', mnemonic: 'DEPORTES - Deh-pohr-tehs is sports' },
  { id: 164, spanish: 'Estudiar', transliteration: 'es-too-dee-ahr', meaning: 'Study', category: 'Verbs', mnemonic: 'ESTUDIAR - Es-too-dee-ahr to study' },
  { id: 165, spanish: 'Trabajar', transliteration: 'trah-bah-hahr', meaning: 'Work', category: 'Verbs', mnemonic: 'TRABAJAR - Trah-bah-hahr to work' },
  { id: 166, spanish: 'Jugar', transliteration: 'hoo-gahr', meaning: 'To play', category: 'Verbs', mnemonic: 'JUGAR - Hoo-gahr to play' },
  { id: 167, spanish: 'Descansar', transliteration: 'des-kahn-sahr', meaning: 'To rest', category: 'Verbs', mnemonic: 'DESCANSAR - Des-kahn-sahr to rest' },
  { id: 168, spanish: 'Trabajar', transliteration: 'trah-bah-hahr', meaning: 'To work', category: 'Verbs', mnemonic: 'TRABAJAR - Trah-bah-hahr to work' },
  { id: 169, spanish: 'Enseñar', transliteration: 'ehn-seh-nyahr', meaning: 'To teach', category: 'Verbs', mnemonic: 'ENSEÑAR - Ehn-seh-nyahr to teach' },
  { id: 170, spanish: 'Aprender', transliteration: 'ah-prehn-dehr', meaning: 'To learn', category: 'Verbs', mnemonic: 'APRENDER - Ah-prehn-dehr to learn' },
  { id: 171, spanish: 'Comenzar', transliteration: 'koh-mehn-sahr', meaning: 'To begin', category: 'Verbs', mnemonic: 'COMENZAR - Koh-mehn-sahr to begin' },
  { id: 172, spanish: 'Terminar', transliteration: 'tehr-mee-nahr', meaning: 'To end', category: 'Verbs', mnemonic: 'TERMINAR - Tehr-mee-nahr to end' },
  { id: 173, spanish: 'Olvidar', transliteration: 'ohl-bee-dahr', meaning: 'To forget', category: 'Verbs', mnemonic: 'OLVIDAR - Ohl-bee-dahr to forget' },
  { id: 174, spanish: 'Recordar', transliteration: 'reh-kohr-dahr', meaning: 'To remember', category: 'Verbs', mnemonic: 'RECORDAR - Reh-kohr-dahr to remember' },
  { id: 175, spanish: 'Entender', transliteration: 'ehn-tehn-dehr', meaning: 'To understand', category: 'Verbs', mnemonic: 'ENTENDER - Ehn-tehn-dehr to understand' },
  { id: 176, spanish: 'Pensar', transliteration: 'pehn-sahr', meaning: 'To think', category: 'Verbs', mnemonic: 'PENSAR - Pehn-sahr to think' },
  { id: 177, spanish: 'Creer', transliteration: 'kreh-ehr', meaning: 'To believe', category: 'Verbs', mnemonic: 'CREER - Kreh-ehr to believe' },
  { id: 178, spanish: 'Sentir', transliteration: 'sehn-teer', meaning: 'To feel', category: 'Verbs', mnemonic: 'SENTIR - Sehn-teer to feel' },
  { id: 179, spanish: 'Reír', transliteration: 'reh-eer', meaning: 'To laugh', category: 'Verbs', mnemonic: 'REÍR - Reh-eer to laugh' },
  { id: 180, spanish: 'Llorar', transliteration: 'yoh-rahr', meaning: 'To cry', category: 'Verbs', mnemonic: 'LLORAR - Yoh-rahr to cry' },
  { id: 181, spanish: 'Cantar', transliteration: 'kahn-tahr', meaning: 'To sing', category: 'Verbs', mnemonic: 'CANTAR - Kahn-tahr to sing' },
  { id: 182, spanish: 'Bailar', transliteration: 'bai-lahr', meaning: 'To dance', category: 'Verbs', mnemonic: 'BAILAR - Bai-lahr to dance' },
  { id: 183, spanish: 'Llevar', transliteration: 'yeh-bahr', meaning: 'To wear', category: 'Verbs', mnemonic: 'LLEVAR - Yeh-bahr to wear' },
  { id: 184, spanish: 'Quitarse', transliteration: 'kee-tahr-seh', meaning: 'To take off', category: 'Verbs', mnemonic: 'QUITARSE - Kee-tahr-seh to take off' },
  { id: 185, spanish: 'Lavar', transliteration: 'lah-bahr', meaning: 'To wash', category: 'Verbs', mnemonic: 'LAVAR - Lah-bahr to wash' },
  { id: 186, spanish: 'Limpiar', transliteration: 'leem-pee-ahr', meaning: 'To clean', category: 'Verbs', mnemonic: 'LIMPIAR - Leem-pee-ahr to clean' },
  { id: 187, spanish: 'Cocinar', transliteration: 'koh-see-nahr', meaning: 'To cook', category: 'Verbs', mnemonic: 'COCINAR - Koh-see-nahr to cook' },
  { id: 188, spanish: 'Cortar', transliteration: 'kohr-tahr', meaning: 'To cut', category: 'Verbs', mnemonic: 'CORTAR - Kohr-tahr to cut' },
  { id: 189, spanish: 'Prestar', transliteration: 'prehs-tahr', meaning: 'To lend', category: 'Verbs', mnemonic: 'PRESTAR - Prehs-tahr to lend' },
  { id: 190, spanish: 'Pedir prestado', transliteration: 'peh-deer prehs-tah-doh', meaning: 'To borrow', category: 'Verbs', mnemonic: 'PEDIR PRESTADO - Peh-deer prehs-tah-doh to borrow' },
  { id: 191, spanish: 'Dar', transliteration: 'dahr', meaning: 'To give', category: 'Verbs', mnemonic: 'DAR - Dahr to give' },
  { id: 192, spanish: 'Recibir', transliteration: 'reh-see-beer', meaning: 'To receive', category: 'Verbs', mnemonic: 'RECIBIR - Reh-see-beer to receive' },
  { id: 193, spanish: 'Enviar', transliteration: 'ehn-bee-ahr', meaning: 'To send', category: 'Verbs', mnemonic: 'ENVIAR - Ehn-bee-ahr to send' },
  { id: 194, spanish: 'Llegar', transliteration: 'yeh-gahr', meaning: 'To arrive', category: 'Verbs', mnemonic: 'LLEGAR - Yeh-gahr to arrive' },
  { id: 195, spanish: 'Buscar', transliteration: 'boos-kahr', meaning: 'To search', category: 'Verbs', mnemonic: 'BUSCAR - Boos-kahr to search' },
  { id: 196, spanish: 'Encontrar', transliteration: 'ehn-kohn-trahr', meaning: 'To find', category: 'Verbs', mnemonic: 'ENCONTRAR - Ehn-kohn-trahr to find' },
  { id: 197, spanish: 'Elegir', transliteration: 'eh-leh-heer', meaning: 'To choose', category: 'Verbs', mnemonic: 'ELEGIR - Eh-leh-heer to choose' },
  { id: 198, spanish: 'Decidir', transliteration: 'deh-see-deer', meaning: 'To decide', category: 'Verbs', mnemonic: 'DECIDIR - Deh-see-deer to decide' },
  { id: 199, spanish: 'Cambiar', transliteration: 'kahm-bee-ahr', meaning: 'To change', category: 'Verbs', mnemonic: 'CAMBIAR - Kahm-bee-ahr to change' },
  { id: 200, spanish: 'Arreglar', transliteration: 'ah-rreh-glahr', meaning: 'To fix', category: 'Verbs', mnemonic: 'ARREGLAR - Ah-rreh-glahr to fix' },
];
