import { Word } from './types';

export const VOCAB_401_500: Word[] = [
  { id: 401, spanish: 'Turista', transliteration: 'too-rees-tah', meaning: 'Tourist', category: 'People', mnemonic: 'TURISTA - Too-rees-tah is tourist' },
  { id: 402, spanish: 'Guía', transliteration: 'gee-ah', meaning: 'Guide', category: 'People', mnemonic: 'GUÍA - Gee-ah is guide' },
  { id: 403, spanish: 'Pasajero', transliteration: 'pah-sah-heh-roh', meaning: 'Passenger', category: 'People', mnemonic: 'PASAJERO - Pah-sah-heh-roh is passenger' },
  { id: 404, spanish: 'Viajero', transliteration: 'bee-ah-heh-roh', meaning: 'Traveler', category: 'People', mnemonic: 'VIAJERO - Bee-ah-heh-roh is traveler' },
  { id: 405, spanish: 'Extranjero', transliteration: 'eks-trahn-heh-roh', meaning: 'Foreigner', category: 'People', mnemonic: 'EXTRANJERO - Eks-trahn-heh-roh is foreigner' },
  { id: 406, spanish: 'Local', transliteration: 'loh-kahl', meaning: 'Local', category: 'People', mnemonic: 'LOCAL - Loh-kahl is local' },
  { id: 407, spanish: 'Ciudadano', transliteration: 'see-oo-dah-dah-noh', meaning: 'Citizen', category: 'People', mnemonic: 'CIUDADANO - See-oo-dah-dah-noh is citizen' },
  { id: 408, spanish: 'Residente', transliteration: 'reh-see-dehn-teh', meaning: 'Resident', category: 'People', mnemonic: 'RESIDENTE - Reh-see-dehn-teh is resident' },
  { id: 409, spanish: 'Inmigrante', transliteration: 'een-mee-grahn-teh', meaning: 'Immigrant', category: 'People', mnemonic: 'INMIGRANTE - Een-mee-grahn-teh is immigrant' },
  { id: 410, spanish: 'Refugiado', transliteration: 'reh-foo-hee-ah-doh', meaning: 'Refugee', category: 'People', mnemonic: 'REFUGIADO - Reh-foo-hee-ah-doh is refugee' },
  { id: 411, spanish: 'Adulto', transliteration: 'ah-dool-toh', meaning: 'Adult', category: 'People', mnemonic: 'ADULTO - Ah-dool-toh is adult' },
  { id: 412, spanish: 'Adolescente', transliteration: 'ah-doh-leh-sehn-teh', meaning: 'Teenager', category: 'People', mnemonic: 'ADOLESCENTE - Ah-doh-leh-sehn-teh is teenager' },
  { id: 413, spanish: 'Bebé', transliteration: 'beh-beh', meaning: 'Baby', category: 'People', mnemonic: 'BEBÉ - Beh-beh is baby' },
  { id: 414, spanish: 'Niña', transliteration: 'nee-nyah', meaning: 'Girl', category: 'People', mnemonic: 'NIÑA - Nee-nyah is girl' },
  { id: 415, spanish: 'Niño', transliteration: 'nee-nyoh', meaning: 'Boy', category: 'People', mnemonic: 'NIÑO - Nee-nyoh is boy' },
  { id: 416, spanish: 'Señora', transliteration: 'seh-nyoh-rah', meaning: 'Mrs / Lady', category: 'People', mnemonic: 'SEÑORA - Seh-nyoh-rah is lady' },
  { id: 417, spanish: 'Señor', transliteration: 'seh-nyohr', meaning: 'Mr / Sir', category: 'People', mnemonic: 'SEÑOR - Seh-nyohr is sir' },
  { id: 418, spanish: 'Señorita', transliteration: 'seh-nyoh-ree-tah', meaning: 'Miss', category: 'People', mnemonic: 'SEÑORITA - Seh-nyoh-ree-tah is miss' },
  { id: 419, spanish: 'Esposo', transliteration: 'es-poh-soh', meaning: 'Husband', category: 'People', mnemonic: 'ESPOSO - Es-poh-soh is husband' },
  { id: 420, spanish: 'Esposa', transliteration: 'es-poh-sah', meaning: 'Wife', category: 'People', mnemonic: 'ESPOSA - Es-poh-sah is wife' },
  { id: 421, spanish: 'Novio', transliteration: 'noh-bee-oh', meaning: 'Boyfriend', category: 'People', mnemonic: 'NOVIO - Noh-bee-oh is boyfriend' },
  { id: 422, spanish: 'Novia', transliteration: 'noh-bee-ah', meaning: 'Girlfriend', category: 'People', mnemonic: 'NOVIA - Noh-bee-ah is girlfriend' },
  { id: 423, spanish: 'Pareja', transliteration: 'pah-reh-hah', meaning: 'Partner', category: 'People', mnemonic: 'PAREJA - Pah-reh-hah is partner' },
  { id: 424, spanish: 'Familia', transliteration: 'fah-mee-lee-ah', meaning: 'Family', category: 'People', mnemonic: 'FAMILIA - Fah-mee-lee-ah is family' },
  { id: 425, spanish: 'Pariente', transliteration: 'pah-ree-ehn-teh', meaning: 'Relative', category: 'People', mnemonic: 'PARIENTE - Pah-ree-ehn-teh is relative' },
  { id: 426, spanish: 'Abuelo', transliteration: 'ah-bweh-loh', meaning: 'Grandfather', category: 'People', mnemonic: 'ABUELO - Ah-bweh-loh is grandfather' },
  { id: 427, spanish: 'Abuela', transliteration: 'ah-bweh-lah', meaning: 'Grandmother', category: 'People', mnemonic: 'ABUELA - Ah-bweh-lah is grandmother' },
  { id: 428, spanish: 'Nieto', transliteration: 'nee-eh-toh', meaning: 'Grandson', category: 'People', mnemonic: 'NIETO - Nee-eh-toh is grandson' },
  { id: 429, spanish: 'Nieta', transliteration: 'nee-eh-tah', meaning: 'Granddaughter', category: 'People', mnemonic: 'NIETA - Nee-eh-tah is granddaughter' },
  { id: 430, spanish: 'Tío', transliteration: 'tee-oh', meaning: 'Uncle', category: 'People', mnemonic: 'TÍO - Tee-oh is uncle' },
  { id: 431, spanish: 'Tía', transliteration: 'tee-ah', meaning: 'Aunt', category: 'People', mnemonic: 'TÍA - Tee-ah is aunt' },
  { id: 432, spanish: 'Primo', transliteration: 'pree-moh', meaning: 'Cousin (male)', category: 'People', mnemonic: 'PRIMO - Pree-moh is cousin' },
  { id: 433, spanish: 'Prima', transliteration: 'pree-mah', meaning: 'Cousin (female)', category: 'People', mnemonic: 'PRIMA - Pree-mah is cousin' },
  { id: 434, spanish: 'Sobrino', transliteration: 'soh-bree-noh', meaning: 'Nephew', category: 'People', mnemonic: 'SOBRINO - Soh-bree-noh is nephew' },
  { id: 435, spanish: 'Sobrina', transliteration: 'soh-bree-nah', meaning: 'Niece', category: 'People', mnemonic: 'SOBRINA - Soh-bree-nah is niece' },
  { id: 436, spanish: 'Suegro', transliteration: 'sweh-groh', meaning: 'Father-in-law', category: 'People', mnemonic: 'SUEGRO - Sweh-groh is father-in-law' },
  { id: 437, spanish: 'Suegra', transliteration: 'sweh-grah', meaning: 'Mother-in-law', category: 'People', mnemonic: 'SUEGRA - Sweh-grah is mother-in-law' },
  { id: 438, spanish: 'Yerno', transliteration: 'yehr-noh', meaning: 'Son-in-law', category: 'People', mnemonic: 'YERNO - Yehr-noh is son-in-law' },
  { id: 439, spanish: 'Nuera', transliteration: 'nweh-rah', meaning: 'Daughter-in-law', category: 'People', mnemonic: 'NUERA - Nweh-rah is daughter-in-law' },
  { id: 440, spanish: 'Cuñado', transliteration: 'koo-nyah-doh', meaning: 'Brother-in-law', category: 'People', mnemonic: 'CUÑADO - Koo-nyah-doh is brother-in-law' },
  { id: 441, spanish: 'Cuñada', transliteration: 'koo-nyah-dah', meaning: 'Sister-in-law', category: 'People', mnemonic: 'CUÑADA - Koo-nyah-dah is sister-in-law' },
  { id: 442, spanish: 'Padrastro', transliteration: 'pah-drahs-troh', meaning: 'Stepfather', category: 'People', mnemonic: 'PADRASTRO - Pah-drahs-troh is stepfather' },
  { id: 443, spanish: 'Madrastra', transliteration: 'mah-drahs-trah', meaning: 'Stepmother', category: 'People', mnemonic: 'MADRASTRA - Mah-drahs-trah is stepmother' },
  { id: 444, spanish: 'Hijastro', transliteration: 'ee-hahs-troh', meaning: 'Stepson', category: 'People', mnemonic: 'HIJASTRO - Ee-hahs-troh is stepson' },
  { id: 445, spanish: 'Hijastra', transliteration: 'ee-hahs-trah', meaning: 'Stepdaughter', category: 'People', mnemonic: 'HIJASTRA - Ee-hahs-trah is stepdaughter' },
  { id: 446, spanish: 'Hermanastro', transliteration: 'ehr-mah-nahs-troh', meaning: 'Stepbrother', category: 'People', mnemonic: 'HERMANASTRO - Ehr-mah-nahs-troh is stepbrother' },
  { id: 447, spanish: 'Hermanastra', transliteration: 'ehr-mah-nahs-trah', meaning: 'Stepsister', category: 'People', mnemonic: 'HERMANASTRA - Ehr-mah-nahs-trah is stepsister' },
  { id: 448, spanish: 'Gemelo', transliteration: 'heh-meh-loh', meaning: 'Twin', category: 'People', mnemonic: 'GEMELO - Heh-meh-loh is twin' },
  { id: 449, spanish: 'Huérfano', transliteration: 'wehr-fah-noh', meaning: 'Orphan', category: 'People', mnemonic: 'HUÉRFANO - Wehr-fah-noh is orphan' },
  { id: 450, spanish: 'Viudo', transliteration: 'bee-oo-doh', meaning: 'Widower', category: 'People', mnemonic: 'VIUDO - Bee-oo-doh is widower' },
  { id: 451, spanish: 'Viuda', transliteration: 'bee-oo-dah', meaning: 'Widow', category: 'People', mnemonic: 'VIUDA - Bee-oo-dah is widow' },
  { id: 452, spanish: 'Soltero', transliteration: 'sohl-teh-roh', meaning: 'Single (male)', category: 'People', mnemonic: 'SOLTERO - Sohl-teh-roh is single' },
  { id: 453, spanish: 'Soltera', transliteration: 'sohl-teh-rah', meaning: 'Single (female)', category: 'People', mnemonic: 'SOLTERA - Sohl-teh-rah is single' },
  { id: 454, spanish: 'Casado', transliteration: 'kah-sah-doh', meaning: 'Married (male)', category: 'People', mnemonic: 'CASADO - Kah-sah-doh is married' },
  { id: 455, spanish: 'Casada', transliteration: 'kah-sah-dah', meaning: 'Married (female)', category: 'People', mnemonic: 'CASADA - Kah-sah-dah is married' },
  { id: 456, spanish: 'Divorciado', transliteration: 'dee-bohr-see-ah-doh', meaning: 'Divorced (male)', category: 'People', mnemonic: 'DIVORCIADO - Dee-bohr-see-ah-doh is divorced' },
  { id: 457, spanish: 'Divorciada', transliteration: 'dee-bohr-see-ah-dah', meaning: 'Divorced (female)', category: 'People', mnemonic: 'DIVORCIADA - Dee-bohr-see-ah-dah is divorced' },
  { id: 458, spanish: 'Comprometido', transliteration: 'kohm-proh-meh-tee-doh', meaning: 'Engaged (male)', category: 'People', mnemonic: 'COMPROMETIDO - Kohm-proh-meh-tee-doh is engaged' },
  { id: 459, spanish: 'Comprometida', transliteration: 'kohm-proh-meh-tee-dah', meaning: 'Engaged (female)', category: 'People', mnemonic: 'COMPROMETIDA - Kohm-proh-meh-tee-dah is engaged' },
  { id: 460, spanish: 'Mascota', transliteration: 'mahs-koh-tah', meaning: 'Pet', category: 'Nature', mnemonic: 'MASCOTA - Mahs-koh-tah is pet' },
  { id: 461, spanish: 'Perro', transliteration: 'peh-rroh', meaning: 'Dog', category: 'Nature', mnemonic: 'PERRO - Peh-rroh is dog' },
  { id: 462, spanish: 'Gato', transliteration: 'gah-toh', meaning: 'Cat', category: 'Nature', mnemonic: 'GATO - Gah-toh is cat' },
  { id: 463, spanish: 'Caballo', transliteration: 'kah-bah-yoh', meaning: 'Horse', category: 'Nature', mnemonic: 'CABALLO - Kah-bah-yoh is horse' },
  { id: 464, spanish: 'Vaca', transliteration: 'bah-kah', meaning: 'Cow', category: 'Nature', mnemonic: 'VACA - Bah-kah is cow' },
  { id: 465, spanish: 'Cerdo', transliteration: 'sehr-doh', meaning: 'Pig', category: 'Nature', mnemonic: 'CERDO - Sehr-doh is pig' },
  { id: 466, spanish: 'Oveja', transliteration: 'oh-beh-hah', meaning: 'Sheep', category: 'Nature', mnemonic: 'OVEJA - Oh-beh-hah is sheep' },
  { id: 467, spanish: 'Cabra', transliteration: 'kah-brah', meaning: 'Goat', category: 'Nature', mnemonic: 'CABRA - Kah-brah is goat' },
  { id: 468, spanish: 'Pollo', transliteration: 'poh-yoh', meaning: 'Chicken', category: 'Nature', mnemonic: 'POLLO - Poh-yoh is chicken' },
  { id: 469, spanish: 'Pato', transliteration: 'pah-toh', meaning: 'Duck', category: 'Nature', mnemonic: 'PATO - Pah-toh is duck' },
  { id: 470, spanish: 'Ganso', transliteration: 'gahn-soh', meaning: 'Goose', category: 'Nature', mnemonic: 'GANSO - Gahn-soh is goose' },
  { id: 471, spanish: 'Conejo', transliteration: 'koh-neh-hoh', meaning: 'Rabbit', category: 'Nature', mnemonic: 'CONEJO - Koh-neh-hoh is rabbit' },
  { id: 472, spanish: 'Ratón', transliteration: 'rah-tohn', meaning: 'Mouse', category: 'Nature', mnemonic: 'RATÓN - Rah-tohn is mouse' },
  { id: 473, spanish: 'Rata', transliteration: 'rah-tah', meaning: 'Rat', category: 'Nature', mnemonic: 'RATA - Rah-tah is rat' },
  { id: 474, spanish: 'Ardilla', transliteration: 'ahr-dee-yah', meaning: 'Squirrel', category: 'Nature', mnemonic: 'ARDILLA - Ahr-dee-yah is squirrel' },
  { id: 475, spanish: 'Oso', transliteration: 'oh-soh', meaning: 'Bear', category: 'Nature', mnemonic: 'OSO - Oh-soh is bear' },
  { id: 476, spanish: 'León', transliteration: 'leh-ohn', meaning: 'Lion', category: 'Nature', mnemonic: 'LEÓN - Leh-ohn is lion' },
  { id: 477, spanish: 'Tigre', transliteration: 'tee-greh', meaning: 'Tiger', category: 'Nature', mnemonic: 'TIGRE - Tee-greh is tiger' },
  { id: 478, spanish: 'Elefante', transliteration: 'eh-leh-fahn-teh', meaning: 'Elephant', category: 'Nature', mnemonic: 'ELEFANTE - Eh-leh-fahn-teh is elephant' },
  { id: 479, spanish: 'Jirafa', transliteration: 'hee-rah-fah', meaning: 'Giraffe', category: 'Nature', mnemonic: 'JIRAFA - Hee-rah-fah is giraffe' },
  { id: 480, spanish: 'Mono', transliteration: 'moh-noh', meaning: 'Monkey', category: 'Nature', mnemonic: 'MONO - Moh-noh is monkey' },
  { id: 481, spanish: 'Serpiente', transliteration: 'sehr-pee-ehn-teh', meaning: 'Snake', category: 'Nature', mnemonic: 'SERPIENTE - Sehr-pee-ehn-teh is snake' },
  { id: 482, spanish: 'Lagarto', transliteration: 'lah-gahr-toh', meaning: 'Lizard', category: 'Nature', mnemonic: 'LAGARTO - Lah-gahr-toh is lizard' },
  { id: 483, spanish: 'Tortuga', transliteration: 'tohr-too-gah', meaning: 'Turtle', category: 'Nature', mnemonic: 'TORTUGA - Tohr-too-gah is turtle' },
  { id: 484, spanish: 'Rana', transliteration: 'rah-nah', meaning: 'Frog', category: 'Nature', mnemonic: 'RANA - Rah-nah is frog' },
  { id: 485, spanish: 'Mariposa', transliteration: 'mah-ree-poh-sah', meaning: 'Butterfly', category: 'Nature', mnemonic: 'MARIPOSA - Mah-ree-poh-sah is butterfly' },
  { id: 486, spanish: 'Abeja', transliteration: 'ah-beh-hah', meaning: 'Bee', category: 'Nature', mnemonic: 'ABEJA - Ah-beh-hah is bee' },
  { id: 487, spanish: 'Hormiga', transliteration: 'ohr-mee-gah', meaning: 'Ant', category: 'Nature', mnemonic: 'HORMIGA - Ohr-mee-gah is ant' },
  { id: 488, spanish: 'Araña', transliteration: 'ah-rah-nyah', meaning: 'Spider', category: 'Nature', mnemonic: 'ARAÑA - Ah-rah-nyah is spider' },
  { id: 489, spanish: 'Mosca', transliteration: 'mohs-kah', meaning: 'Fly', category: 'Nature', mnemonic: 'MOSCA - Mohs-kah is fly' },
  { id: 490, spanish: 'Mosquito', transliteration: 'mohs-kee-toh', meaning: 'Mosquito', category: 'Nature', mnemonic: 'MOSQUITO - Mohs-kee-toh is mosquito' },
  { id: 491, spanish: 'Delfín', transliteration: 'dehl-feen', meaning: 'Dolphin', category: 'Nature', mnemonic: 'DELFÍN - Dehl-feen is dolphin' },
  { id: 492, spanish: 'Ballena', transliteration: 'bah-yeh-nah', meaning: 'Whale', category: 'Nature', mnemonic: 'BALLENA - Bah-yeh-nah is whale' },
  { id: 493, spanish: 'Tiburón', transliteration: 'tee-boo-rohn', meaning: 'Shark', category: 'Nature', mnemonic: 'TIBURÓN - Tee-boo-rohn is shark' },
  { id: 494, spanish: 'Pulpo', transliteration: 'pool-poh', meaning: 'Octopus', category: 'Nature', mnemonic: 'PULPO - Pool-poh is octopus' },
  { id: 495, spanish: 'Calamar', transliteration: 'kah-lah-mahr', meaning: 'Squid', category: 'Nature', mnemonic: 'CALAMAR - Kah-lah-mahr is squid' },
  { id: 496, spanish: 'Cangrejo', transliteration: 'kahn-greh-hoh', meaning: 'Crab', category: 'Nature', mnemonic: 'CANGREJO - Kahn-greh-hoh is crab' },
  { id: 497, spanish: 'Camarón', transliteration: 'kah-mah-rohn', meaning: 'Shrimp', category: 'Nature', mnemonic: 'CAMARÓN - Kah-mah-rohn is shrimp' },
  { id: 498, spanish: 'Estrella de mar', transliteration: 'es-treh-yah deh mahr', meaning: 'Starfish', category: 'Nature', mnemonic: 'ESTRELLA DE MAR - Es-treh-yah deh mahr is starfish' },
  { id: 499, spanish: 'Medusa', transliteration: 'meh-doo-sah', meaning: 'Jellyfish', category: 'Nature', mnemonic: 'MEDUSA - Meh-doo-sah is jellyfish' },
  { id: 500, spanish: 'Coral', transliteration: 'koh-rahl', meaning: 'Coral', category: 'Nature', mnemonic: 'CORAL - Koh-rahl is coral' },
];
