import { Word } from './types';

export const VOCAB_301_400: Word[] = [
  { id: 301, spanish: 'Hábil', transliteration: 'ah-beel', meaning: 'Skillful', category: 'Adjectives', mnemonic: 'HÁBIL - Ah-beel is skillful' },
  { id: 302, spanish: 'Malo en', transliteration: 'mah-loh ehn', meaning: 'Bad at', category: 'Adjectives', mnemonic: 'MALO EN - Mah-loh ehn is bad at' },
  { id: 303, spanish: 'Arriba', transliteration: 'ah-rree-bah', meaning: 'Above', category: 'Objects', mnemonic: 'ARRIBA - Ah-rree-bah is above' },
  { id: 304, spanish: 'Abajo', transliteration: 'ah-bah-hoh', meaning: 'Below', category: 'Objects', mnemonic: 'ABAJO - Ah-bah-hoh is below' },
  { id: 305, spanish: 'Frente', transliteration: 'frehn-teh', meaning: 'Front', category: 'Objects', mnemonic: 'FRENTE - Frehn-teh is front' },
  { id: 306, spanish: 'Detrás', transliteration: 'deh-trahs', meaning: 'Behind', category: 'Objects', mnemonic: 'DETRÁS - Deh-trahs is behind' },
  { id: 307, spanish: 'Izquierda', transliteration: 'ees-kee-ehr-dah', meaning: 'Left', category: 'Objects', mnemonic: 'IZQUIERDA - Ees-kee-ehr-dah is left' },
  { id: 308, spanish: 'Derecha', transliteration: 'deh-reh-chah', meaning: 'Right', category: 'Objects', mnemonic: 'DERECHA - Deh-reh-chah is right' },
  { id: 309, spanish: 'Dentro', transliteration: 'dehn-troh', meaning: 'Inside', category: 'Objects', mnemonic: 'DENTRO - Dehn-troh is inside' },
  { id: 310, spanish: 'Afuera', transliteration: 'ah-fweh-rah', meaning: 'Outside', category: 'Objects', mnemonic: 'AFUERA - Ah-fweh-rah is outside' },
  { id: 311, spanish: 'Al lado', transliteration: 'ahl lah-doh', meaning: 'Next to', category: 'Objects', mnemonic: 'AL LADO - Ahl lah-doh is next to' },
  { id: 312, spanish: 'Allí', transliteration: 'ah-yee', meaning: 'There', category: 'Objects', mnemonic: 'ALLÍ - Ah-yee is there' },
  { id: 313, spanish: 'Aquí', transliteration: 'ah-kee', meaning: 'Here', category: 'Objects', mnemonic: 'AQUÍ - Ah-kee is here' },
  { id: 314, spanish: 'Este', transliteration: 'es-teh', meaning: 'This', category: 'Objects', mnemonic: 'ESTE - Es-teh is this' },
  { id: 315, spanish: 'Ese', transliteration: 'eh-seh', meaning: 'That', category: 'Objects', mnemonic: 'ESE - Eh-seh is that' },
  { id: 316, spanish: 'Dónde', transliteration: 'dohn-deh', meaning: 'Where', category: 'Objects', mnemonic: 'DÓNDE - Dohn-deh is where' },
  { id: 317, spanish: 'Lugar', transliteration: 'loo-gahr', meaning: 'Place', category: 'Objects', mnemonic: 'LUGAR - Loo-gahr is place' },
  { id: 318, spanish: 'Momento', transliteration: 'moh-mehn-toh', meaning: 'Time', category: 'Time', mnemonic: 'MOMENTO - Moh-mehn-toh is moment' },
  { id: 319, spanish: 'Qué', transliteration: 'keh', meaning: 'What', category: 'Objects', mnemonic: 'QUÉ - Keh is what' },
  { id: 320, spanish: 'Cuándo', transliteration: 'kwahn-doh', meaning: 'When', category: 'Time', mnemonic: 'CUÁNDO - Kwahn-doh is when' },
  { id: 321, spanish: 'Quién', transliteration: 'kee-ehn', meaning: 'Who', category: 'People', mnemonic: 'QUIÉN - Kee-ehn is who' },
  { id: 322, spanish: 'Por qué', transliteration: 'pohr keh', meaning: 'Why', category: 'Objects', mnemonic: 'POR QUÉ - Pohr keh is why' },
  { id: 323, spanish: 'Cómo', transliteration: 'koh-moh', meaning: 'How', category: 'Objects', mnemonic: 'CÓMO - Koh-moh is how' },
  { id: 324, spanish: 'Cuánto', transliteration: 'kwahn-toh', meaning: 'How much', category: 'Numbers', mnemonic: 'CUÁNTO - Kwahn-toh is how much' },
  { id: 325, spanish: 'Color', transliteration: 'koh-lohr', meaning: 'Color', category: 'Objects', mnemonic: 'COLOR - Koh-lohr is color' },
  { id: 326, spanish: 'Forma', transliteration: 'fohr-mah', meaning: 'Shape', category: 'Objects', mnemonic: 'FORMA - Fohr-mah is shape' },
  { id: 327, spanish: 'Tamaño', transliteration: 'tah-mah-nyoh', meaning: 'Size', category: 'Objects', mnemonic: 'TAMAÑO - Tah-mah-nyoh is size' },
  { id: 328, spanish: 'Número', transliteration: 'noo-meh-roh', meaning: 'Number', category: 'Numbers', mnemonic: 'NÚMERO - Noo-meh-roh is number' },
  { id: 329, spanish: 'Nombre', transliteration: 'nohm-breh', meaning: 'Name', category: 'People', mnemonic: 'NOMBRE - Nohm-breh is name' },
  { id: 330, spanish: 'Dirección', transliteration: 'dee-rehk-see-ohn', meaning: 'Address', category: 'Objects', mnemonic: 'DIRECCIÓN - Dee-rehk-see-ohn is address' },
  { id: 331, spanish: 'Número', transliteration: 'noo-meh-roh', meaning: 'Number', category: 'Numbers', mnemonic: 'NÚMERO - Noo-meh-roh is number' },
  { id: 332, spanish: 'Edad', transliteration: 'eh-dahd', meaning: 'Age', category: 'People', mnemonic: 'EDAD - Eh-dahd is age' },
  { id: 333, spanish: 'Cumpleaños', transliteration: 'koom-pleh-ah-nyohs', meaning: 'Birthday', category: 'Time', mnemonic: 'CUMPLEAÑOS - Koom-pleh-ah-nyohs is birthday' },
  { id: 334, spanish: 'País', transliteration: 'pah-ees', meaning: 'Country', category: 'Objects', mnemonic: 'PAÍS - Pah-ees is country' },
  { id: 335, spanish: 'Ciudad', transliteration: 'see-oo-dahd', meaning: 'City', category: 'Objects', mnemonic: 'CIUDAD - See-oo-dahd is city' },
  { id: 336, spanish: 'Pueblo', transliteration: 'pweh-bloh', meaning: 'Village', category: 'Objects', mnemonic: 'PUEBLO - Pweh-bloh is village' },
  { id: 337, spanish: 'Camino', transliteration: 'kah-mee-noh', meaning: 'Road', category: 'Objects', mnemonic: 'CAMINO - Kah-mee-noh is road' },
  { id: 338, spanish: 'Puente', transliteration: 'pwehn-teh', meaning: 'Bridge', category: 'Objects', mnemonic: 'PUENTE - Pwehn-teh is bridge' },
  { id: 339, spanish: 'Edificio', transliteration: 'eh-dee-fee-see-oh', meaning: 'Building', category: 'Objects', mnemonic: 'EDIFICIO - Eh-dee-fee-see-oh is building' },
  { id: 340, spanish: 'Parque', transliteration: 'pahr-keh', meaning: 'Park', category: 'Objects', mnemonic: 'PARQUE - Pahr-keh is park' },
  { id: 341, spanish: 'Biblioteca', transliteration: 'bee-blee-oh-teh-kah', meaning: 'Library', category: 'Objects', mnemonic: 'BIBLIOTECA - Bee-blee-oh-teh-kah is library' },
  { id: 342, spanish: 'Museo', transliteration: 'moo-seh-oh', meaning: 'Museum', category: 'Objects', mnemonic: 'MUSEO - Moo-seh-oh is museum' },
  { id: 343, spanish: 'Exposición', transliteration: 'eks-poh-see-see-ohn', meaning: 'Exhibition', category: 'Objects', mnemonic: 'EXPOSICIÓN - Eks-poh-see-see-ohn is exhibition' },
  { id: 344, spanish: 'Zoológico', transliteration: 'soh-oh-loh-hee-koh', meaning: 'Zoo', category: 'Objects', mnemonic: 'ZOOLÓGICO - Soh-oh-loh-hee-koh is zoo' },
  { id: 345, spanish: 'Acuario', transliteration: 'ah-kwah-ree-oh', meaning: 'Aquarium', category: 'Objects', mnemonic: 'ACUARIO - Ah-kwah-ree-oh is aquarium' },
  { id: 346, spanish: 'Parque de diversiones', transliteration: 'pahr-keh deh dee-behr-see-oh-nehs', meaning: 'Amusement park', category: 'Objects', mnemonic: 'PARQUE DE DIVERSIONES - Pahr-keh deh dee-behr-see-oh-nehs is amusement park' },
  { id: 347, spanish: 'Templo', transliteration: 'tehm-ploh', meaning: 'Temple', category: 'Objects', mnemonic: 'TEMPLO - Tehm-ploh is temple' },
  { id: 348, spanish: 'Iglesia', transliteration: 'ee-gleh-see-ah', meaning: 'Church', category: 'Objects', mnemonic: 'IGLESIA - Ee-gleh-see-ah is church' },
  { id: 349, spanish: 'Mezquita', transliteration: 'mehs-kee-tah', meaning: 'Mosque', category: 'Objects', mnemonic: 'MEZQUITA - Mehs-kee-tah is mosque' },
  { id: 350, spanish: 'Sinagoga', transliteration: 'see-nah-goh-gah', meaning: 'Synagogue', category: 'Objects', mnemonic: 'SINAGOGA - See-nah-goh-gah is synagogue' },
  { id: 351, spanish: 'Mercado', transliteration: 'mehr-kah-doh', meaning: 'Market', category: 'Objects', mnemonic: 'MERCADO - Mehr-kah-doh is market' },
  { id: 352, spanish: 'Supermercado', transliteration: 'soo-pehr-mehr-kah-doh', meaning: 'Supermarket', category: 'Objects', mnemonic: 'SUPERMERCADO - Soo-pehr-mehr-kah-doh is supermarket' },
  { id: 353, spanish: 'Centro comercial', transliteration: 'sehn-troh koh-mehr-see-ahl', meaning: 'Shopping mall', category: 'Objects', mnemonic: 'CENTRO COMERCIAL - Sehn-troh koh-mehr-see-ahl is mall' },
  { id: 354, spanish: 'Farmacia', transliteration: 'fahr-mah-see-ah', meaning: 'Pharmacy', category: 'Objects', mnemonic: 'FARMACIA - Fahr-mah-see-ah is pharmacy' },
  { id: 355, spanish: 'Correo', transliteration: 'koh-rreh-oh', meaning: 'Post office', category: 'Objects', mnemonic: 'CORREO - Koh-rreh-oh is post office' },
  { id: 356, spanish: 'Policía', transliteration: 'poh-lee-see-ah', meaning: 'Police', category: 'People', mnemonic: 'POLICÍA - Poh-lee-see-ah is police' },
  { id: 357, spanish: 'Bombero', transliteration: 'bohm-beh-roh', meaning: 'Firefighter', category: 'People', mnemonic: 'BOMBERO - Bohm-beh-roh is firefighter' },
  { id: 358, spanish: 'Doctor', transliteration: 'dohk-tohr', meaning: 'Doctor', category: 'People', mnemonic: 'DOCTOR - Dohk-tohr is doctor' },
  { id: 359, spanish: 'Enfermera', transliteration: 'ehn-fehr-meh-rah', meaning: 'Nurse', category: 'People', mnemonic: 'ENFERMERA - Ehn-fehr-meh-rah is nurse' },
  { id: 360, spanish: 'Dentista', transliteration: 'dehn-tees-tah', meaning: 'Dentist', category: 'People', mnemonic: 'DENTISTA - Dehn-tees-tah is dentist' },
  { id: 361, spanish: 'Abogado', transliteration: 'ah-boh-gah-doh', meaning: 'Lawyer', category: 'People', mnemonic: 'ABOGADO - Ah-boh-gah-doh is lawyer' },
  { id: 362, spanish: 'Ingeniero', transliteration: 'een-heh-nee-eh-roh', meaning: 'Engineer', category: 'People', mnemonic: 'INGENIERO - Een-heh-nee-eh-roh is engineer' },
  { id: 363, spanish: 'Arquitecto', transliteration: 'ahr-kee-tehk-toh', meaning: 'Architect', category: 'People', mnemonic: 'ARQUITECTO - Ahr-kee-tehk-toh is architect' },
  { id: 364, spanish: 'Artista', transliteration: 'ahr-tees-tah', meaning: 'Artist', category: 'People', mnemonic: 'ARTISTA - Ahr-tees-tah is artist' },
  { id: 365, spanish: 'Músico', transliteration: 'moo-see-koh', meaning: 'Musician', category: 'People', mnemonic: 'MÚSICO - Moo-see-koh is musician' },
  { id: 366, spanish: 'Cantante', transliteration: 'kahn-tahn-teh', meaning: 'Singer', category: 'People', mnemonic: 'CANTANTE - Kahn-tahn-teh is singer' },
  { id: 367, spanish: 'Actor', transliteration: 'ahk-tohr', meaning: 'Actor', category: 'People', mnemonic: 'ACTOR - Ahk-tohr is actor' },
  { id: 368, spanish: 'Escritor', transliteration: 'es-kree-tohr', meaning: 'Writer', category: 'People', mnemonic: 'ESCRITOR - Es-kree-tohr is writer' },
  { id: 369, spanish: 'Periodista', transliteration: 'peh-ree-oh-dees-tah', meaning: 'Journalist', category: 'People', mnemonic: 'PERIODISTA - Peh-ree-oh-dees-tah is journalist' },
  { id: 370, spanish: 'Fotógrafo', transliteration: 'foh-toh-grah-foh', meaning: 'Photographer', category: 'People', mnemonic: 'FOTÓGRAFO - Foh-toh-grah-foh is photographer' },
  { id: 371, spanish: 'Cocinero', transliteration: 'koh-see-neh-roh', meaning: 'Chef', category: 'People', mnemonic: 'COCINERO - Koh-see-neh-roh is chef' },
  { id: 372, spanish: 'Camarero', transliteration: 'kah-mah-reh-roh', meaning: 'Waiter', category: 'People', mnemonic: 'CAMARERO - Kah-mah-reh-roh is waiter' },
  { id: 373, spanish: 'Conductor', transliteration: 'kohn-dook-tohr', meaning: 'Driver', category: 'People', mnemonic: 'CONDUCTOR - Kohn-dook-tohr is driver' },
  { id: 374, spanish: 'Piloto', transliteration: 'pee-loh-toh', meaning: 'Pilot', category: 'People', mnemonic: 'PILOTO - Pee-loh-toh is pilot' },
  { id: 375, spanish: 'Marinero', transliteration: 'mah-ree-neh-roh', meaning: 'Sailor', category: 'People', mnemonic: 'MARINERO - Mah-ree-neh-roh is sailor' },
  { id: 376, spanish: 'Soldado', transliteration: 'sohl-dah-doh', meaning: 'Soldier', category: 'People', mnemonic: 'SOLDADO - Sohl-dah-doh is soldier' },
  { id: 377, spanish: 'Granjero', transliteration: 'grahn-heh-roh', meaning: 'Farmer', category: 'People', mnemonic: 'GRANJERO - Grahn-heh-roh is farmer' },
  { id: 378, spanish: 'Pescador', transliteration: 'pes-kah-dohr', meaning: 'Fisherman', category: 'People', mnemonic: 'PESCADOR - Pes-kah-dohr is fisherman' },
  { id: 379, spanish: 'Carpintero', transliteration: 'kahr-peen-teh-roh', meaning: 'Carpenter', category: 'People', mnemonic: 'CARPINTERO - Kahr-peen-teh-roh is carpenter' },
  { id: 380, spanish: 'Electricista', transliteration: 'eh-lehk-tree-sees-tah', meaning: 'Electrician', category: 'People', mnemonic: 'ELECTRICISTA - Eh-lehk-tree-sees-tah is electrician' },
  { id: 381, spanish: 'Plomero', transliteration: 'ploh-meh-roh', meaning: 'Plumber', category: 'People', mnemonic: 'PLOMERO - Ploh-meh-roh is plumber' },
  { id: 382, spanish: 'Mecánico', transliteration: 'meh-kah-nee-koh', meaning: 'Mechanic', category: 'People', mnemonic: 'MECÁNICO - Meh-kah-nee-koh is mechanic' },
  { id: 383, spanish: 'Científico', transliteration: 'see-ehn-tee-fee-koh', meaning: 'Scientist', category: 'People', mnemonic: 'CIENTÍFICO - See-ehn-tee-fee-koh is scientist' },
  { id: 384, spanish: 'Programador', transliteration: 'proh-grah-mah-dohr', meaning: 'Programmer', category: 'People', mnemonic: 'PROGRAMADOR - Proh-grah-mah-dohr is programmer' },
  { id: 385, spanish: 'Diseñador', transliteration: 'dee-seh-nyah-dohr', meaning: 'Designer', category: 'People', mnemonic: 'DISEÑADOR - Dee-seh-nyah-dohr is designer' },
  { id: 386, spanish: 'Gerente', transliteration: 'heh-rehn-teh', meaning: 'Manager', category: 'People', mnemonic: 'GERENTE - Heh-rehn-teh is manager' },
  { id: 387, spanish: 'Secretario', transliteration: 'seh-kreh-tah-ree-oh', meaning: 'Secretary', category: 'People', mnemonic: 'SECRETARIO - Seh-kreh-tah-ree-oh is secretary' },
  { id: 388, spanish: 'Contador', transliteration: 'kohn-tah-dohr', meaning: 'Accountant', category: 'People', mnemonic: 'CONTADOR - Kohn-tah-dohr is accountant' },
  { id: 389, spanish: 'Vendedor', transliteration: 'behn-deh-dohr', meaning: 'Salesperson', category: 'People', mnemonic: 'VENDEDOR - Behn-deh-dohr is salesperson' },
  { id: 390, spanish: 'Cliente', transliteration: 'klee-ehn-teh', meaning: 'Customer', category: 'People', mnemonic: 'CLIENTE - Klee-ehn-teh is customer' },
  { id: 391, spanish: 'Jefe', transliteration: 'heh-feh', meaning: 'Boss', category: 'People', mnemonic: 'JEFE - Heh-feh is boss' },
  { id: 392, spanish: 'Empleado', transliteration: 'ehm-pleh-ah-doh', meaning: 'Employee', category: 'People', mnemonic: 'EMPLEADO - Ehm-pleh-ah-doh is employee' },
  { id: 393, spanish: 'Colega', transliteration: 'koh-leh-gah', meaning: 'Colleague', category: 'People', mnemonic: 'COLEGA - Koh-leh-gah is colleague' },
  { id: 394, spanish: 'Amigo', transliteration: 'ah-mee-goh', meaning: 'Friend', category: 'People', mnemonic: 'AMIGO - Ah-mee-goh is friend' },
  { id: 395, spanish: 'Enemigo', transliteration: 'eh-neh-mee-goh', meaning: 'Enemy', category: 'People', mnemonic: 'ENEMIGO - Eh-neh-mee-goh is enemy' },
  { id: 396, spanish: 'Vecino', transliteration: 'beh-see-noh', meaning: 'Neighbor', category: 'People', mnemonic: 'VECINO - Beh-see-noh is neighbor' },
  { id: 397, spanish: 'Extraño', transliteration: 'eks-trah-nyoh', meaning: 'Stranger', category: 'People', mnemonic: 'EXTRAÑO - Eks-trah-nyoh is stranger' },
  { id: 398, spanish: 'Invitado', transliteration: 'een-bee-tah-doh', meaning: 'Guest', category: 'People', mnemonic: 'INVITADO - Een-bee-tah-doh is guest' },
  { id: 399, spanish: 'Anfitrión', transliteration: 'ahn-fee-tree-ohn', meaning: 'Host', category: 'People', mnemonic: 'ANFITRIÓN - Ahn-fee-tree-ohn is host' },
  { id: 400, spanish: 'Visitante', transliteration: 'bee-see-tahn-teh', meaning: 'Visitor', category: 'People', mnemonic: 'VISITANTE - Bee-see-tahn-teh is visitor' },
];
